server:
  port: 9094

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    instance:
      prefer-ip-address: true
    service-url:
      defaultZone: http://localhost:9090/eureka

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/hotels/**

        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/ratings/**
